import { DomeniuType, DomeniuInfo } from "./types";

export type { DomeniuType };

export const domenii: DomeniuInfo[] = [
  {
    id: 'sanitare',
    nume: 'Instalații Sanitare',
    icon: '💧',
    color: 'text-blue-400',
    bgColor: 'bg-blue-600',
    descriere: 'Apă rece, apă caldă, canalizare menajeră și pluvială',
  },
  {
    id: 'termice',
    nume: 'Instalații Termice',
    icon: '🔥',
    color: 'text-red-400',
    bgColor: 'bg-red-600',
    descriere: 'Încălzire, pardoseală caldă, centrale, panouri solare',
  },
  {
    id: 'racire-ventilatie',
    nume: 'Răcire și Ventilație',
    icon: '❄️',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-600',
    descriere: 'AC comfort, ventilație, recuperare căldură',
  },
  {
    id: 'frigorifice',
    nume: 'Instalații Frigorifice',
    icon: '🧊',
    color: 'text-indigo-400',
    bgColor: 'bg-indigo-600',
    descriere: 'Cicluri frigorifice, refrigeranți, camere frigorifice',
  },
  {
    id: 'electrice',
    nume: 'Instalații Electrice',
    icon: '⚡',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-600',
    descriere: 'Iluminat, forță JT și MT, protecții, împământare',
  },
  {
    id: 'gaze',
    nume: 'Instalații de Gaze',
    icon: '🔶',
    color: 'text-orange-400',
    bgColor: 'bg-orange-600',
    descriere: 'Gaze naturale la utilizator și rețele',
  },
  {
    id: 'isi',
    nume: 'Siguranță la Foc',
    icon: '🧯',
    color: 'text-red-500',
    bgColor: 'bg-red-700',
    descriere: 'ISI, hidranți, sprinklere, spălare fum',
  },
  {
    id: 'cladiri-speciale',
    nume: 'Clădiri Speciale',
    icon: '🏢',
    color: 'text-purple-400',
    bgColor: 'bg-purple-600',
    descriere: 'Multizonale, case pasive, case inteligente',
  },
  {
    id: 'automatizari',
    nume: 'Automatizări și BMS',
    icon: '🤖',
    color: 'text-violet-400',
    bgColor: 'bg-violet-600',
    descriere: 'Domotică, KNX, BACnet, control PID, senzori',
  },
  {
    id: 'eficienta-energetica',
    nume: 'Eficiență Energetică',
    icon: '🌱',
    color: 'text-green-400',
    bgColor: 'bg-green-600',
    descriere: 'Audit, certificare, energii regenerabile, cogenerare',
  },
  {
    id: 'hidroedilitare',
    nume: 'Hidroedilitare',
    icon: '🌐',
    color: 'text-teal-400',
    bgColor: 'bg-teal-600',
    descriere: 'Aductiuni, rețele apă și canalizare oraș/sate',
  },
  {
    id: 'management',
    nume: 'Management și Resurse',
    icon: '📊',
    color: 'text-pink-400',
    bgColor: 'bg-pink-600',
    descriere: 'FM, KPI, LCC, gestiune apă',
  },
  {
    id: 'fundamente',
    nume: 'Fundamente',
    icon: '📐',
    color: 'text-gray-400',
    bgColor: 'bg-gray-600',
    descriere: 'Unități, conversii, proprietăți fizice, matematică',
  },
];